version: "3.8"
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MEILISEARCH_HOST=${MEILISEARCH_HOST}
      - MEILISEARCH_API_KEY=${MEILISEARCH_API_KEY}
    restart: unless-stopped
